config/routes.rb
StickerApp::Application.routes.draw do
  resources :stickers

end

app/models/sticker.rb
class Sticker < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/stickers_controller.rb
class StickersController < ApplicationController
  before_action :set_sticker, only: [:show, :edit, :update, :destroy]

  # GET /stickers
  # GET /stickers.json
  def index
    @stickers = Sticker.all
  end

  # GET /stickers/1
  # GET /stickers/1.json
  def show
  end

  # GET /stickers/new
  def new
    @sticker = Sticker.new
  end

  # GET /stickers/1/edit
  def edit
  end

  # POST /stickers
  # POST /stickers.json
  def create
    @sticker = Sticker.new(sticker_params)

    respond_to do |format|
      if @sticker.save
        format.html { redirect_to @sticker, notice: 'Sticker was successfully created.' }
        format.json { render action: 'show', status: :created, location: @sticker }
      else
        format.html { render action: 'new' }
        format.json { render json: @sticker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stickers/1
  # PATCH/PUT /stickers/1.json
  def update
    respond_to do |format|
      if @sticker.update(sticker_params)
        format.html { redirect_to @sticker, notice: 'Sticker was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @sticker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stickers/1
  # DELETE /stickers/1.json
  def destroy
    @sticker.destroy
    respond_to do |format|
      format.html { redirect_to stickers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sticker
      @sticker = Sticker.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sticker_params
      params.require(:sticker).permit(:text, :position_x, :position_y)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stickers_helper.rb
module StickersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StickerApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="sticker-board">
		<h1>Sticker Board</h1>
	</div>
</body>
</html>

app/views/stickers/_form.html.erb
<%= form_for(@sticker) do |f| %>
  <% if @sticker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sticker.errors.count, "error") %> prohibited this sticker from being saved:</h2>

      <ul>
      <% @sticker.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_field :text %>
  </div>
  <div class="field">
    <%= f.label :position_x %><br>
    <%= f.number_field :position_x %>
  </div>
  <div class="field">
    <%= f.label :position_y %><br>
    <%= f.number_field :position_y %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stickers/edit.html.erb
<h1>Editing sticker</h1>

<%= render 'form' %>

<%= link_to 'Show', @sticker %> |
<%= link_to 'Back', stickers_path %>

app/views/stickers/index.html.erb
<h1>Listing stickers</h1>

<table>
  <thead>
    <tr>
      <th>Text</th>
      <th>Position x</th>
      <th>Position y</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @stickers.each do |sticker| %>
      <tr>
        <td><%= sticker.text %></td>
        <td><%= sticker.position_x %></td>
        <td><%= sticker.position_y %></td>
        <td><%= link_to 'Show', sticker %></td>
        <td><%= link_to 'Edit', edit_sticker_path(sticker) %></td>
        <td><%= link_to 'Destroy', sticker, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sticker', new_sticker_path %>

app/views/stickers/new.html.erb
<h1>New sticker</h1>

<%= render 'form' %>

<%= link_to 'Back', stickers_path %>

app/views/stickers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @sticker.text %>
</p>

<p>
  <strong>Position x:</strong>
  <%= @sticker.position_x %>
</p>

<p>
  <strong>Position y:</strong>
  <%= @sticker.position_y %>
</p>

<%= link_to 'Edit', edit_sticker_path(@sticker) %> |
<%= link_to 'Back', stickers_path %>